### ISSUE TITLE
Can't update conf been updated before

### ISSUE THREAD

**Issue by AP1001** [hilanderas/routing#10]
# Can't update conf been updated before

### Test environment
* dev-16.04-dhcp-single-0.0.12
* ubuntu 16.04 x86

### How to reproduce
* make install
* make update(do some change)
* make update
### Actual results
Changes did in first update didn't show in second update
### Expected results
Changes did in first update didn't show in second update, so that I can keep changing them

**Comment by Valerio-Perez** [comment]
That seems a bug. Thank you for your test! @AP1001

**Comment by Valerio-Perez** [comment]
Fix in `0.0.13`.

**Comment by AP1001** [comment]
Same issue in dev-16.04-pppoe-dual-0.0.13 and dev-16.04-ppoe-single-0.0.13

**Comment by Valerio-Perez** [comment]
Yes, i find the problem in code. Thank you for testing! @AP1001
