### ISSUE TITLE
Test state command is not consistent in gitbook

### ISSUE THREAD

**Issue by Valerio-Perez** [hilanderas/routing#3]
# Issue description
when I test with the gitbook, I find the test state command is not consistent between `QAUSAGE/Production` and `More Scenarios/How to check state`.

### Test environment
* commit: 3fad51a8cbb0e21e7c9879929ce765a2bfe8faf0

### How to reproduce
Open the gitbook of routing.

### Actual results
In `QAUSAGE/Production`, command is `make -s test_test_state`.
But in `More Scenarios/How to check state`, command is `make test_state`.

### Expected results
They are consistent.

**Comment by AP1001** [comment]
@Valerio-Perez They are not same, test_state is interface of routing project, test_test_state is the interface I defined in test flow
