### ISSUE TITLE
Worry state check of RUNNING state

### ISSUE THREAD

**Issue by Valerio-Perez** [hilanderas/routing#4]
# Issue description
The RUNNING state tells that `Config_queue exists - False`

### Test environment
* commit: 3fad51a8cbb0e21e7c9879929ce765a2bfe8faf0

### How to reproduce
Open the gitbook

### Actual results
`Config_queue exists - False` in RUNNING state.

### Expected results
`Config_queue exists - True` in RUNNING state.

**Comment by AP1001** [comment]
Fixed
