### ISSUE TITLE
The test state command has no services status check

### ISSUE THREAD

**Issue by Valerio-Perez** [hilanderas/routing#5]
# Issue description
RT

### Test environment
* Package and version : `0.0.12`

**Comment by AP1001** [comment]
OK, do you need check status every time when you check state?

**Comment by Valerio-Perez** [comment]
Yes, and i want that it does not report error when the services not exist or failed.

**Comment by Valerio-Perez** [comment]
Fix in [0.0.13](https://github.com/hilanderas/routing/releases/tag/0.0.13)
