### ISSUE TITLE
No explanation of state attributes

### ISSUE THREAD

**Issue by Valerio-Perez** [hilanderas/routing#6]
# Issue description
RT

### Test environment
* Package and version : `0.0.11`

**Comment by AP1001** [comment]
What do you mean? I have an explanation here in [How to check state](https://hilanderas.github.io/routing/usage/morescenarios/STATE.html)

**Comment by Valerio-Perez** [comment]
Cause it is different between package, the explanation may be different.

**Comment by AP1001** [comment]
Attributes explanation is in there own page

**Comment by AP1001** [comment]
Done

**Comment by Valerio-Perez** [comment]
@AP1001 This will make a enhancement in code.

**Comment by AP1001** [comment]
[github page updated](https://hilanderas.github.io/routing/usage/morescenarios/STATE.html)
